services:
  mysql:
    image: mysql:8.4.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zoopervisor
      MYSQL_USER: zoopervisor
      MYSQL_PASSWORD: zoopervisor
      LANG: C.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5