services:
  mysql-test:
    image: mysql:8.4.2
    container_name: zoopervisor-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zoopervisor_test
      LANG: C.UTF-8
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10